# Generated by Django 3.1.14 on 2024-01-05 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microservicesapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='api_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
