# Generated by Django 3.1.14 on 2024-01-05 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microservicesapp', '0003_activitylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUserManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='password',
        ),
    ]
